### ISSUE TITLE
fromJson factory constructor

### ISSUE THREAD

**Issue by SunlightBro** [simc/crimson#11]
I really like the factory constructor syntax from json_serializable, to be able to call `Model.fromJson(uint8List)`.
I'm aware this would just be syntactic-sugar with out much value, but could help migrating from json_serializable to crimson, and it could be just optionally.

<details><summary>Example what I mean</summary>
<p>

**If** there is a factory constructor that returns `_$<className>(buffer)` (_or some other name convention_)
```dart
@json
class Model {
  // ...
  factory Model.fromJson(List<int> buffer) => _$Model(buffer);
}
```
**then** generate additional extensions like so:
```dart
Model _$Model(List<int> buffer) => ModelExt.fromJson(buffer);

extension ModelExt on Model {
  static Model fromJson(List<int> buffer) {
    final crimson = Crimson(buffer);
    return crimson.readModel();
  }

  Uint8List toJson() {
    final writer = CrimsonWriter();
    writer.writeModel(this);
    return writer.toBytes();
  }
}

extension ModelList on List<Model> {
  static List<Model> fromJson(List<int> buffer) {
    final crimson = Crimson(buffer);
    return crimson.readModelList();
  }

  Uint8List toJson() {
    final writer = CrimsonWriter();
    writer.writeModelList(this);
    return writer.toBytes();
  }
}
```
then you can call
```dart
final Model model = Model.fromJson(singleModelUint8List);
final Uint8List foo = model.toJson();

final List<Model> list = ModelList.fromJson(listUint8List);
final Uint8List bar = list.toJson();
```

</p>
</details>

If this is something you want I can create a PR.

**Comment by simc** [comment]
I really like this idea. I think it would be a great addition 🙏

**Comment by SunlightBro** [comment]
@simc Do you have maybe a tip on how to use break-point and step through the build_runner ?
currently I'm just adding print and try'n'error to see if my changes have the desired effects.

**Comment by SunlightBro** [comment]
@simc After working on it for a while now, the only way to make it work (together with `freezed`) is to always use `@Freezed(fromJson: false, toJson: false)`
<details>
  <summary>Example</summary>
  
  ```dart
@Freezed(fromJson: false, toJson: false)
class FJFreezed with _$FJFreezed {
  // ignore: invalid_annotation_target
  @json
  const factory FJFreezed({
    required String name,
    required int age,
  }) = _FJFreezed;

  factory FJFreezed.fromJson(List<int> buffer) => _$FJFreezedFromJson(buffer);
}
  ```
</details>

which makes it quite unintuitive to use.
