### ISSUE TITLE
Mutable models

### ISSUE THREAD

**Issue by hawkkiller** [simc/crimson#14]
The idea of having mutable models is bad from the start and has known limitations and issues.

**Comment by simc** [comment]
Would you mind explaining what you mean by this? If you prefer final properties you're free to do so.

**Comment by hawkkiller** [comment]
As I can see in the example you have mutable model with all the nullable fields. Generator also iteratively fills that model, I don't see any possibilities to make them final and not nullable.

**Comment by simc** [comment]
It's just an example. Final fields work just fine with Crimson

**Comment by hawkkiller** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/62852417/215345293-d186ffcf-4696-46de-870c-6f9ae54bd1b9.png">
How?

**Comment by simc** [comment]
Add a constructor with these properties. This class makes no sense without
