### ISSUE TITLE
Add rename field to json annotation and build.yaml

### ISSUE THREAD

**Issue by Reprevise** [simc/crimson#6]
Due to varying field naming conventions, Crimson should have support for renaming all fields in a class by providing an enum value to the json annotation with whatever case the fields come in. All that is provided currently is the `name` field on the `JsonField` annotation. `json_serializable` has support for `kebab`, `screamingSnake`, `pascal`, and `snake` via its `FieldRename` enum. This should also apply to enums as well.

**Comment by simc** [comment]
Just implemented this. You can now use `@jsonKebabCase` and `@jsonSnakeCase`. Check out the readme 🙂
